[book]
authors = ["shutosha"]
language = "en"
multilingual = false
src = "src"
title = "deepDive"
description = "A deep dive into various topics with Gemini."

[output.html]
cname = "deepdive.shutri.com"
mathjax-support = true
