[book]
authors = ["ashutosh jain"]
language = "en"
multilingual = false
src = "src"
title = "deepDive"
description = "A deep dive into various topics with Gemini."

[output.html]
mathjax-support = true
cname = "deepdive.shutri.com"
additional-css = ["theme/custom.css"]
